---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=20
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=5starget:
    kind: Deployment
    name: (kustomize-controller|helm-controller|source-controller)
resources:
- gotk-components.yaml
- gotk-sync.yaml
