---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: kube-system
spec:
  chart:
    spec:
      chart: longhorn
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: "*"
  interval: 30m
  values:
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
      autoCleanupSnapshotWhenDeleteBackup: true
      backupCompressionMethod: gzip
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      removeSnapshotsDuringFilesystemTrim: true
      replicaAutoBalance: least-effort
      rwxVolumeFastFailover: true
    persistence:
      defaultClass: true
      defaultDataLocality: best-effort
      nfsOptions: async,hard,nfsvers=4,noatime,proto=tcp,retrans=2,rsize=65536,timeo=600,wsize=65536
      reclaimPolicy: Delete
