---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: apps
spec:
  chart:
    spec:
      chart: radarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: truecharts
  interval: 50m
  values:
    common:
      ingress:
        main:
          integrations:
            traefik:
              enabled: false
    metrics:
      main:
        enabled: false
    persistence:
      config:
        size: 50Mi
        type: emptyDir
    portal:
      open:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOME: /tmp
                RADARR__APP__LAUNCHBROWSER: "False"
                RADARR__APP__THEME: dark
                RADARR__AUTH__METHOD: Forms
                RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
                RADARR__LOG__ANALYTICSENABLED: "False"
                RADARR__LOG__DBENABLED: "False"
                RADARR__LOG__LEVEL: info
