---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  encryptedData: {}
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: longhorn-system
    type: Opaque
