---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-filesystem-trim
  namespace: storage
spec:
  concurrency: 2
  cron: 30 3 * * *
  groups:
  - default
  task: filesystem-trim
