---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-filesystem-trim
  namespace: kube-system
spec:
  concurrency: 2
  cron: 30 0 * * *
  groups:
    - default
  task: filesystem-trim
