---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-secret
  namespace: storage
spec:
  encryptedData: {}
  template:
    metadata:
      name: longhorn-backup-secret
      namespace: storage
    type: Opaque
