---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: kube-system
spec:
  concurrency: 2
  cron: 0 3 * * *
  groups:
    - default
  retain: 1
  task: backup
