name: template-sync

on:
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@6e1d0089686f8940604fc15baae62367bf6ee860 # v2.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: kanya-approve/oracle-talos-flux-example
