name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@e2882a16ccc484c672ed2b98aace1e91dee1d29b # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@e2882a16ccc484c672ed2b98aace1e91dee1d29b # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@e2882a16ccc484c672ed2b98aace1e91dee1d29b # main
      - name: Validate manifests
        run: ./scripts/validate.sh
