name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@992c220c423e137a6c1808828d8bc569249abc12 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@992c220c423e137a6c1808828d8bc569249abc12 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@992c220c423e137a6c1808828d8bc569249abc12 # main
      - name: Validate manifests
        run: ./scripts/validate.sh
